# Generated by Django 3.1.2 on 2020-10-16 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.video')),
            ],
        ),
    ]
