# Generated by Django 3.1.2 on 2020-10-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='duration_time',
            field=models.FloatField(default=0),
        ),
    ]
