# Generated by Django 3.1.2 on 2020-10-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201027_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='duration_time',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='pause_time',
            field=models.FloatField(default=0, null=True),
        ),
    ]
