# Generated by Django 3.1.2 on 2020-10-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201027_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='subtitle',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbtail',
            field=models.URLField(blank=True),
        ),
    ]
