# Generated by Django 3.1.2 on 2020-10-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='user_response',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
