# Generated by Django 3.1.2 on 2020-10-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201029_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='duration_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='pause_time',
            field=models.FloatField(default=0),
        ),
    ]
