# Generated by Django 3.1.2 on 2020-10-21 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_flag_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('thumbtail', models.ImageField(blank=True, upload_to='')),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('premium', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='upload_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='playlist_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.playlist')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.video')),
            ],
        ),
    ]
