# Generated by Django 3.1.2 on 2020-11-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201029_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='thumbtail',
            field=models.URLField(blank=True, max_length=20000),
        ),
    ]
