# Generated by Django 3.1.2 on 2020-10-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201021_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='upload_date',
            field=models.DateTimeField(),
        ),
    ]
