# Generated by Django 3.1.2 on 2020-10-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_flag_user_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
