# Generated by Django 3.1.2 on 2020-10-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201018_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='name',
            field=models.CharField(default='heeee', max_length=50),
            preserve_default=False,
        ),
    ]
