# Generated by Django 3.1.2 on 2020-10-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_playlist_video_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist_video',
            name='datetime',
            field=models.DateTimeField(default='2016-05-18T15:37:36.993048Z'),
            preserve_default=False,
        ),
    ]
