# Generated by Django 3.1.2 on 2020-10-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_playlist_video_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='subtitle',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
