# Generated by Django 3.1.2 on 2020-10-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='payperview',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
